/**
 * Invitation token helpers.
 *
 * An invitation is a one-shot signup link generated by an admin. The
 * URL itself is the bearer credential — anyone with the link can claim
 * the account at the pre-assigned role.
 *
 * Tokens are random base64url strings (no signing — the row in the
 * `invitations` table IS the credential store; presence + unconsumed +
 * not-expired = valid). The DB unique constraint on `token` plus the
 * acceptedAt-null check is the entire validation.
 *
 * Default TTL: 7 days. Tunable per-call.
 */
import { drizzle } from "drizzle-orm/d1";
import { and, eq, isNull } from "drizzle-orm";
import { nanoid } from "nanoid";
import * as schema from "../content/schema";

export type InvitationRole = "admin" | "editor" | "author";

export const DEFAULT_INVITE_TTL_HOURS = 24 * 7; // 7 days

/** Crypto-strong base64url token. ~22 chars, ~128 bits of entropy. */
export function generateInviteToken(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

export interface CreateInviteInput {
  email: string;
  role: InvitationRole;
  createdBy: string;
  ttlHours?: number;
}

export async function createInvitation(
  d1: D1Database,
  input: CreateInviteInput,
): Promise<{ id: string; token: string; expiresAt: string }> {
  const db = drizzle(d1, { schema });
  const id = nanoid();
  const token = generateInviteToken();
  const ttl = input.ttlHours ?? DEFAULT_INVITE_TTL_HOURS;
  const expiresAt = new Date(Date.now() + ttl * 3600 * 1000).toISOString();

  await db.insert(schema.invitations).values({
    id,
    email: input.email.trim().toLowerCase(),
    role: input.role,
    token,
    expiresAt,
    createdBy: input.createdBy,
  });

  return { id, token, expiresAt };
}

export interface InviteLookup {
  id: string;
  email: string;
  role: InvitationRole;
  expiresAt: string;
  acceptedAt: string | null;
}

/**
 * Resolve a token to its invitation row. Returns the row regardless of
 * acceptance/expiry state so callers can return granular error messages
 * ("expired" vs "already used").
 */
export async function findInvitationByToken(
  d1: D1Database,
  token: string,
): Promise<InviteLookup | null> {
  const db = drizzle(d1, { schema });
  const row = await db
    .select({
      id: schema.invitations.id,
      email: schema.invitations.email,
      role: schema.invitations.role,
      expiresAt: schema.invitations.expiresAt,
      acceptedAt: schema.invitations.acceptedAt,
    })
    .from(schema.invitations)
    .where(eq(schema.invitations.token, token))
    .get();
  return (row as InviteLookup | undefined) ?? null;
}

/** Mark an invitation row as consumed. Returns false if the row was already used. */
export async function consumeInvitation(
  d1: D1Database,
  invitationId: string,
  acceptedUserId: string,
): Promise<boolean> {
  const db = drizzle(d1, { schema });
  const now = new Date().toISOString();
  const result = await db
    .update(schema.invitations)
    .set({ acceptedAt: now, acceptedUserId })
    .where(
      and(
        eq(schema.invitations.id, invitationId),
        isNull(schema.invitations.acceptedAt),
      ),
    )
    .run();
  return (result.meta?.changes ?? 0) > 0;
}

/** List all invitations (for the /cms/users page). */
export async function listInvitations(d1: D1Database) {
  const db = drizzle(d1, { schema });
  return db.select().from(schema.invitations).all();
}

export async function revokeInvitation(
  d1: D1Database,
  invitationId: string,
): Promise<void> {
  const db = drizzle(d1, { schema });
  await db
    .delete(schema.invitations)
    .where(eq(schema.invitations.id, invitationId));
}
